name: Tests

on: ["push", "pull_request"]

jobs:
  build:
    name: PHP ${{ matrix.php }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - 8.1
          - 8.2
          - 8.3
          - 8.4

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - run: composer validate --strict

      # TODO re-add caching
      - run: composer install --prefer-dist --no-progress --no-suggest

      - run: composer run test

      - run: composer run lint -- --dry-run
        if: ${{ matrix.php == '8.1' }}
